version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: family-media-app-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network

  # 以下部分可选，如果你想同时启动后端
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: family-media-app-backend
    ports:
      - "5000:5000"
    volumes:
      - ../media:/app/media
    restart: unless-stopped
    environment:
      - SECRET_KEY=a8s7d9f87asdf897as9df87a9s8d7f9a8s7df98as7df
      - DEFAULT_USER=family
      - DEFAULT_PASSWORD=123456
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 