version: '3.8'

services:
  # 后端服务 (连接到独立的Qdrant数据库)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ihomemedia-backend
    restart: unless-stopped
    env_file:
      - .local.env
    environment:
      # 从.local.env文件加载环境变量
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - MEDIA_DIR=/media
      - QDRANT_URL=http://localhost:6333
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=false
      - TEXT_TO_TEXT_THRESHOLD=${TEXT_TO_TEXT_THRESHOLD:-0.8}
      - TEXT_TO_IMAGE_THRESHOLD=${TEXT_TO_IMAGE_THRESHOLD:-0.2}
      - IMAGE_SEARCH_THRESHOLD=${IMAGE_SEARCH_THRESHOLD:-0.5}
    volumes:
      - /media:/media
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 前端服务 (包含Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ihomemedia-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 